### ISSUE TITLE
Working with Coq 8.5, Coq 8.6

### ISSUE THREAD

**Issue by Ptival** [aa755/CFGV#1]
Hello,

I've been trying to use CFGV to see if it would actually keep its promises in my use case, but found out the code is not 8.5/8.6 ready.

I have managed to port it with only minor difficulty though:

https://github.com/Ptival/CFGV/tree/coq-8.5

https://github.com/Ptival/CFGV/tree/coq-8.6

Is there any interest in integrating those changes?

**Comment by aa755** [comment]
Thanks. I cloned your branches to this repo.

Also, CFGV may be overkill for many applications.  If possible, I would instead recommend the [SquiggleEq](https://github.com/aa755/SquiggleEq) library, which is a less general solution to the same problem. The extra generality of CFGV sometimes makes CFGV more cumbersome to use. 
The SquiggleEq library also has an abstract de-bruijn representation. Also, I have used the SquiggleEq library in many non-toy projects.
